### ISSUE TITLE
[Bugfix] Naming conflict

### ISSUE THREAD

**Issue by maxmosk** [mregorova/Onegin#1]
This function declaration creates a shading of the library function name. Perhaps even the standard does not require explicitly allowing the occurrence of repetition in the case of C. In C++, this (probably) only works because of the existence of function overloading.This function declaration creates a shading of the library function name. Perhaps even the standard does not require an explicit resolution of the resulting repetition in the C slice. In C++, this (probably) only works because of the existence of function overloading.  
https://github.com/mregorova/Onegin/blob/8d16b95359e63e8b6e00c03a2a0823b8f8943c11/onegin2.cpp#L114  
It might be wise to add a prefix to distinguish the function names of this library. For example, the name `txt_free` will cause a similar situation with much less probability.

**Comment by mregorova** [comment]
Thank you, done.
